### ISSUE TITLE
OCn (nodes with 2 inflow 1 outflow)

### ISSUE THREAD

**Issue by nportilloda** [lucarraro/OCNet#2]
Hi! I'm trying to generate an OCn with a grid size of 250 by 250, I would like that all the nodes have a maximum of 2 inflows (Basically that when I aggregate the reaches I only find the downNode once or twice). Is there a way to do set this when building the network? 
I want to avoid what is happening in the following picture, where reach 181 has inflows from 187, 188 and 177
![image](https://user-images.githubusercontent.com/63715922/142939671-ed474c5d-8bfe-4869-92fa-703b3a0d0d72.png)

**Comment by lucarraro** [comment]
Hello,
I'm sorry but there is no formal way to impose that. 
A trick would be rewiring one single node at the FD level, transforming the 3-inflow connection in a sequence of 2-inflow connections. I prepared an example from `OCN_250_T`, which is a 250x250 OCN included in the package.

`rm(list=ls())`
`library(OCNet)`
`library(Matrix) # sparse matrices for solution of linear system`

`OCN <- OCN_250_T`
`OCN <- landscape_OCN(OCN)`
`OCN <- aggregate_OCN(OCN, thrA=75) # with default value for thrA, there is no node with 3 inflows`

`node3_AG <- which(colSums(OCN$AG$W)==3) # find AG node with 3 inflows (only 1 such node in this case)`
`node3_FD <- OCN$AG$toFD[node3_AG] # correspondent of node3_AG at FD level`

`# find the neighbour of node_newDown_FD, as the node to be rewired must belong to this group`
`# if saveN8=TRUE in create_OCN, there is no need to do the following: one can just use OCN$N8$W to retrieve the neighbouring nodes`
`X_node <- OCN$FD$X[node3_FD] # X of target node`
`Y_node <- OCN$FD$Y[node3_FD] # Y of target node`
`# Y and Y of neighbouring nodes`
`X_neigh <- rep(c(X_node-OCN$cellsize, X_node, X_node+OCN$cellsize),3)`
`Y_neigh <- c(rep(Y_node-OCN$cellsize,3),rep(Y_node,3),rep(Y_node+OCN$cellsize,3))`
`# find neighbouring nodes`
`neigh_FD <- numeric(9)`
`for (i in 1:9){ neigh_FD[i] <- which(OCN$FD$X==X_neigh[i] & OCN$FD$Y==Y_neigh[i])}`
`# extract A and downNode for the neighbour of node3_FD
`A_neigh <- OCN$FD$A[neigh_FD]`
`downNode_neigh <- OCN$FD$downNode[neigh_FD]`

Once `neigh_FD`, `A_neigh` and `downNode_neigh` are calculated, the easiest thing is to make a sketch of the flow direction patterns in the neighbour of the target node:
![rewireOCN-01](https://user-images.githubusercontent.com/44206471/142999823-87f9f0f2-1526-4e55-9a29-413e94a848a4.png)

If we rewire node 25220 into 25219, we avoid the 3-inflow connection:

`# REWIRE NODE`
`OCN$FD$downNode[25220] <- 25219`
`OCN$FD$W[25220, node3_FD] <- 0`
`OCN$FD$W[25220, 25219] <- 1`
`OCN$FD$W <- as.spam(OCN$FD$W) # remove 0 from entries of sparse matrix`

`# recalculate A from solution of linear system`
`A <- solve(Diagonal(OCN$FD$nNodes,1) - t(as.dgCMatrix.spam(OCN$FD$W)), 1+numeric(OCN$FD$nNodes))`
`A <- as.numeric(A)*OCN$cellsize^2`
`OCN$FD$A <- A`

`# now run landscape_OCN and aggregate_OCN`
`OCN <- landscape_OCN(OCN)`
`OCN <- aggregate_OCN(OCN, thrA=75)`
`max(colSums(OCN$AG$W)) # =2, i.e. no more 3-inflow connections` 

A faster alternative would be to increase `thrA` in `aggregate_OCN`, as 3-inflow connections tend to disappear when only large branches are kept in the river network.

**Comment by nportilloda** [comment]
Great thanks, I'll give that a try and get back to you if I have any more questions!
