### ISSUE TITLE
Error in OCN_to_SSN when obsDesign is systematic

### ISSUE THREAD

**Issue by fseaton** [lucarraro/OCNet#3]
Hello,

Whenever I try to turn an OCN into a SSN object with a systematic design I get a rather strange error message back - `Error in .local(obj, ...): NA values in coordinates`. I've tried changing the systematicDesign arguments, the size of the OCN, and the level argument but I can't seem to get anywhere with it. Any ideas on what might be causing it? I can use createSSN from the SSN package with a systematic design fine.

Example:
```
library(OCNet)
library(SSN)
set.seed(63786435)

dimsize <- 50
OCN <- create_OCN(dimsize,dimsize,outletPos = sample.int(dimsize,1))

OCN <- landscape_OCN(OCN, slope0 = 0.1)

OCN <- aggregate_OCN(OCN)

# Try to convert to SSN object with structured design...
SSN_struct <- OCN_to_SSN(OCN, obsDesign = systematicDesign(spacing = 1),
                         path = paste0(tempdir(),"/ocn.ssn"), 
                         level = "AG")
# Error in .local(obj, ...) : NA values in coordinates
```

Thank you!
Fiona

**Comment by lucarraro** [comment]
Dear Fiona,

Thanks for your interesting question. 

I think what is happening here is that `systematicDesign(spacing = 1)` tries to insert a node inside every reach, while by definition in OCNet the reach departing from the outlet has null length (i.e., `OCN$AG$leng[OCN$AG$outlet]=0`). If you set, say, `OCN$AG$leng[OCN$AG$outlet]=OCN$cellsize` after your call to `aggregate_OCN`, then the call to `OCN_to_SSN` should work.

Let me know if this fixes the issue.

Cheers,
Luca

**Comment by fseaton** [comment]
Thanks Luca, that fixed it!
